name: Build and publish new Demo Apps

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  beginner-demo-app-dockerhub:
    name: Build and publish BeginnerDemo container images to DockerHub
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Stable
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/beginner-demo
          path: ./beginner-demo
          tag: stable
          cache: false
#          extra_args: "--cache-repo levoai/levo-demoapp-cache"

      - name: Versioned
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/beginner-demo
          path: ./beginner-demo
          cache: false
#          extra_args: "--cache-repo levoai/levo-demoapp-cache"
          strip_tag_prefix: v
